name: CI Trigger

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-frontend:
    uses: ./.github/workflows/microservice-ci.yaml
    with:
      service: frontend
